services:
  database:
    extends:
      file: database/posgres-db.yml
      service: postgresdb
  notifications-rmq:
    extends:
      file: rabbitmq/rabbitmq.yml
      service: notifications-rmq
  reciever:
    extends:
      file: notification-reciever/node-reciever.yml
      service: nodejs-reciever
  mail:
    extends:
      file: mail/mailpit-compose.yml
      service: mailpit
volumes:
  postgres_data: