services:
  database:
    extends:
      file: database/posgres-db.yml
      service: postgresdb
  notifications-rmq:
    extends:
      file: rabbitmq/rabbitmq.yml
      service: notifications-rmq
  reciever:
    extends:
      file: notification-reciever/node-reciever.yml
      service: nodejs-reciever
  #pgadmin:
  #  extends:
  #    file: pg-admin/pg-admin.yml
  #    service: pgadmin
volumes:
  postgres_data: