spring.profiles.active=default
spring.main.banner-mode=CONSOLE
spring.output.ansi.enabled=ALWAYS
server.use-forward-headers=true
server.port=9084
server.servlet.context-path=/api

# Security
spring.security.api-key = seba-123

# PostgreSQL database properties
spring.datasource.url = jdbc:postgresql://localhost:5432/notifications-db
spring.datasource.username=user
spring.datasource.password=password

# Hibernate properties
spring.jpa.hibernate.dll-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.generate-ddl = false
spring.jpa.hibernate.naming.implicit-strategy = org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

#Hikari pool.
spring.datasource.hikari.pool-name=pool
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.leak-detection-threshold=2000

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=rmq
spring.rabbitmq.password=rmqpass
logging.level.org.springframework.amqp=DEBUG
logging.level.org.springframework.boot.autoconfigure.amqp=DEBUG

# -- Management.
management.endpoints.web.exposure.include=health,loggers,metrics
management.endpoint.loggers.enabled=true
management.endpoint.health.enabled=true
management.endpoint.metrics.enabled = true
management.tracing.enabled=false
logging.level.com.zaxxer.hikari=WARN
logging.level.org.springframework.jdbc.datasource=INFO
