FROM quay.io/wildfly/wildfly:32.0.0.Final-jdk21

# Copiamos el WAR al directorio de deployments
COPY target/*.war /opt/jboss/wildfly/standalone/deployments/app.war

# (Opcional) usuario de management
RUN /opt/jboss/wildfly/bin/add-user.sh admin admin --silent

EXPOSE 8080 9990

CMD ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0"]